import Slider from "@/components/slider/slider";
import SectionElement from "@/components/section-element/section-element";
import Head from "next/head";
import styles from "./index.module.scss";
import cs from "classnames";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={cs(styles["first-full-screen"])}>
          <Slider />
          <SectionElement />
        </div>
      </main>
    </>
  );
}
