import Slider from "@/components/main-page-sections/slider/slider";
import Head from "next/head";
import styles from "./index.module.scss";
import cs from "classnames";
import AboutMe from "@/components/main-page-sections/about-me/about-me";
import ClassicTravel from "@/components/main-page-sections/travel/classic-travel";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={cs(styles["first-full-screen"])}>
          <Slider />
          <AboutMe />
          <ClassicTravel />
        </div>
      </main>
    </>
  );
}
